#!/usr/bin/env python
import argparse

from PIL import Image


def main(path):
    Image.open(path).show()


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("path")
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    main(**vars(args))
